services:
  mysql:
    image: mysql:8.4
    container_name: arena_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arena
      MYSQL_USER: arena
      MYSQL_PASSWORD: arena123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  back-end:
    image: maven:3.9-eclipse-temurin-25
    container_name: arena_backend
    working_dir: /app
    command: sh -c "./mvnw spring-boot:run"
    volumes:
      - ./back-end:/app
      - maven_cache:/root/.m2
      - uploads_data:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/arena
      SPRING_DATASOURCE_USERNAME: arena
      SPRING_DATASOURCE_PASSWORD: arena123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      APP_UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy


  front-end:
    image: node:22-alpine
    container_name: arena_frontend
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start"
    volumes:
      - ./front-end:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - back-end

volumes:
  mysql_data:
  maven_cache:
  uploads_data:
  frontend_node_modules:
